### ISSUE TITLE
core-static is not found

### ISSUE THREAD

**Issue by dell1503** [mimir-chatbot/reverse-proxy-example#1]
Hi there,

This drives me crazy.
I'm somehow stucked.

So thank you very much for you work, great!
However when I run it, and call the cat, the Login Screen doesn't show the right css / logo.
In Dev Tools I see that the URL is not available: https://cheshire-cat-core/core-static/img/logo.svg

I don't get it why.

Here is my Compose of the cat:
```
    env_file:
       - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      # Timezone
      - CCAT_CORS_FORWARDED_ALLOW_IPS="*"
      - CCAT_CORE_HOST=localhost
      - CCAT_CORE_PORT=1865
      - CCAT_QDRANT_HOST=cheshire-cat-vector-memory
      - CCAT_QDRANT_PORT=6333
      - CCAT_CORE_USE_SECURE_PROTOCOLS=false
```

And here the variable I set via .env File:
```
# Decide to use https / wss secure protocols
CCAT_CORE_USE_SECURE_PROTOCOLS=true

# Uvicorn and FastAPI operating behind https proxy
CCAT_HTTPS_PROXY_MODE=true
```

Thy Nginx is part is working fine.
Here the Conf:

```
server {
    listen  80;
    listen 443 default_server ssl;

    listen  [::]:80;

    server_name  localhost;
    client_max_body_size 3000M;

    ssl_certificate /etc/nginx/ssl/nginx.crt;
    ssl_certificate_key /etc/nginx/ssl/nginx.key;

    location / {
        proxy_pass http://cheshire-cat-core/;
    }

    location /ws {
        proxy_pass http://cheshire-cat-core/ws;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host;
    }
}
```

What do I miss?
